name: starkwager
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.15
  freezed_annotation: ^2.4.1
  go_router: ^14.6.2
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.2.3
  appcheck: ^1.5.2
  image_picker: ^1.1.2
  reown_appkit: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  test: ^1.25.2
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  flutter_lints: ^5.0.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    #- assets/animations/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware


  fonts:
    - family: General Sans
      fonts:
        - asset: assets/fonts/GeneralSans-Variable.ttf
        - asset: assets/fonts/GeneralSans-Medium.otf
        - asset: assets/fonts/GeneralSans-Regular.otf
        - asset: assets/fonts/GeneralSans-Light.otf
        - asset: assets/fonts/GeneralSans-Extralight.otf
        - asset: assets/fonts/GeneralSans-Semibold.otf
        - asset: assets/fonts/GeneralSans-Bold.otf

scripts:
  build_runner: fvm flutter pub run build_runner build

